### ISSUE TITLE
Update modulefiles to combine with UFS-WM NOAH-MP subcomponent

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/land-DA_workflow#4]
- Add dual functionality to build UFS-WM -DAPP=ATML application in the ecbuild-based land-DA_workflow cmake system
- Set UFS-WM as submodule and utilize compile.sh and run_compile.sh scripts
- Additional build scripts can be added to CMakeLists.txt
- Depends on unified spack-stack maintenance on RDHPCS and PW-Cloud platforms: need to prioritize hera/orion cases first
- Follow-up is needed with https://github.com/ufs-community/ufs-weather-model/issues/1651

**Comment by ulmononian** [comment]
i created a new ufswm fork branch that utilizes the official spack-stack unified environment in its module files (currently only orion is updated): https://github.com/ulmononian/ufs-weather-model/blob/feature/spack_stack_ue/modulefiles/ufs_orion.intel.lua. 

this can be used to test the build of the ufswm `-DAPP=ATML` component as part of the `ecbuild` step for an updated land DA worklow `CMakeLists.txt`.

additionally, i updated the hera and orion land DA modulefiles in my fork of the release branch here: https://github.com/ulmononian/land-offline_workflow/tree/release/public-v1.0.0/modulefiles. these utilize the spack-stack unified-environment with associated new builds of the fv3-bundle w/ this stack. however, the fv3-bundle may need to be rebuilt considering results mentioned in #2.
