### ISSUE TITLE
Git cloning issue (missing ufs-land-driver/ccpp-physics submodule pointer) with different git versions

### ISSUE THREAD

**Issue by rhaesung** [ufs-community/land-DA_workflow#5]
- Looks like the old git version doesn’t support the git cloning in Orion and RDHPCS Cloud platform (AWS, GCP, and Azure), where by default the git versions loaded are 1.8.3.1.

- Complete and successful clones are reported on Hera/Jet (2.18.0) and Cheyenne/Gaea (2.26.2).

**Comment by jkbk2004** [comment]
@rhaesung it the problem is resolved, can we close this issue?
