### ISSUE TITLE
Rename 'docs' to 'doc'

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/land-DA_workflow#59]
NCO prefers `doc` to `docs` as the name of the documentation directory.

**Comment by chan-hoo** [comment]
@gspetro-NOAA, we'll need to update the User's guide of the land-DA workflow before the new delivery. Could you change the `docs` directory to `doc` as you did for SRW when you update the document?

**Comment by gspetro-NOAA** [comment]
@chan-hoo Yes! That is one of the changes I've made in the PR I'm working on (not opened yet, but hopefully soon).
